apiVersion: v1
kind: Service
metadata:
  name: circleguard-gateway-service
  namespace: circleguard-prod
spec:
  type: LoadBalancer
  selector:
    app: circleguard-gateway-service
  ports:
    - port: 80
      targetPort: 8080
