apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-file-service
  namespace: circleguard-dev
  labels:
    app: circleguard-file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-file-service
  template:
    metadata:
      labels:
        app: circleguard-file-service
    spec:
      containers:
        - name: circleguard-file-service
          image: circleguard-file-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_JSON
              value: '{"management":{"metrics":{"distribution":{"percentiles-histogram":{"http.server.requests":true}}}}}'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
