from locust import HttpUser, task, between
import requests

class AuthUser(HttpUser):
    host = "http://localhost:8081"
    wait_time = between(1, 3)

    def on_start(self):
        # Initial login to obtain token
        response = self.client.post("/api/v1/auth/login", json={"username": "admin", "password": "password"})
        if response.status_code == 200 and "accessToken" in response.json():
            self.token = response.json()["accessToken"]
        else:
            self.token = None

    @task(3)
    def login_stress(self):
        self.client.post("/api/v1/auth/login", json={"username": "admin", "password": "password"})

    @task(2)
    def token_validation(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        self.client.get("/api/v1/auth/validate", headers=headers)


class FormUser(HttpUser):
    host = "http://localhost:8083"
    wait_time = between(1, 3)

    def on_start(self):
        auth_url = "http://localhost:8081/api/v1/auth/login"
        try:
            response = requests.post(auth_url, json={"username": "admin", "password": "password"})
            if response.status_code == 200 and "accessToken" in response.json():
                self.token = response.json()["accessToken"]
            else:
                self.token = None
        except Exception:
            self.token = None

    @task(3)
    def form_submission_load(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        self.client.post("/api/v1/questionnaires", json={
            "title": "Load Test Form",
            "description": "Generated by Locust",
            "active": True
        }, headers=headers)

    @task(2)
    def dashboard_concurrent_reads(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        self.client.get("/api/v1/questionnaires", headers=headers)

    @task(1)
    def file_upload_stress(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        files = {"file": ("test.txt", b"dummy content", "text/plain")}
        self.client.post("/api/v1/attachments", files=files, headers=headers)