sonar.projectKey=JRuiz1601_circle-guard-public
sonar.organization=jruiz1601
sonar.projectName=CircleGuard
sonar.sources=services
sonar.java.binaries=services/*/build/classes/java/main
sonar.java.test.binaries=services/*/build/classes/java/test
sonar.exclusions=**/build/**,**/bin/**,mobile/**,terraform/**
sonar.coverage.exclusions=**/*Application.java,**/*Config.java
