loki:
  enabled: true
  persistence:
    enabled: false

promtail:
  enabled: true
  podLabels:
    app: promtail

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false

prometheus:
  enabled: false
