apiVersion: v1
kind: Service
metadata:
  name: circleguard-identity-service
  namespace: circleguard-dev
spec:
  type: ClusterIP
  selector:
    app: circleguard-identity-service
  ports:
    - port: 80
      targetPort: 8082
