apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-app-sa
  namespace: circleguard-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: circleguard-app-role
  namespace: circleguard-prod
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: circleguard-app-rb
  namespace: circleguard-prod
subjects:
  - kind: ServiceAccount
    name: circleguard-app-sa
    namespace: circleguard-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: circleguard-app-role
