apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
  namespace: circleguard-dev
  labels:
    app: circleguard-promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      containers:
        - name: circleguard-promotion-service
          image: circleguard-promotion-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_JSON
              value: '{"management":{"metrics":{"distribution":{"percentiles-histogram":{"http.server.requests":true}}}}}'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "circleguard-kafka:29092"
            - name: NEO4J_URI
              value: "bolt://circleguard-neo4j:7687"
            - name: SPRING_NEO4J_URI
              value: "bolt://circleguard-neo4j:7687"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/circleguard_promotion"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
