apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
  namespace: circleguard-dev
  labels:
    app: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      containers:
        - name: circleguard-form-service
          image: circleguard-form-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/circleguard_form"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "circleguard-kafka:29092"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
